# .scrutinizer.yml
imports:
    - javascript
    - php

# FIXME: find a way to keep excluded_paths list sorted
filter:
    excluded_paths: [ html/includes/geshi/*, html/includes/jpgraph/*, html/js/*, includes/phpmailer/*, html/css/*, html/includes/Slim/*, includes/console_color.php, includes/console_table.php ]
