sudo: required
language: php
addons:
  chrome: stable
services:
  - mysql
env:
  global:
    APP_ENV=testing
matrix:
  fast_finish: true
  include:
  - php: 7.4
    env: SKIP_STYLE_CHECK=1 SKIP_DUSK_CHECK=1
  - php: 7.3
    env: SKIP_UNIT_CHECK=1 CHROME_HEADLESS=1
  - php: 7.2
    env: SKIP_STYLE_CHECK=1 SKIP_DUSK_CHECK=1 EXECUTE_BUILD_DOCS=true

cache:
  directories:
    - vendor
    - $HOME/.cache/pip
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y snmp fping python3-pip python3-setuptools
  - mysql -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - cp tests/config/config.test.php config.php

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - pip3 install --user snmpsim PyMySQL pylint
  - test -n "$SKIP_DUSK_CHECK" || php artisan dusk:update --detect

after_failure:
  - tail /tmp/snmpsimd.log

before_script:
  - phpenv config-rm xdebug.ini

script:
  - php artisan dev:check ci
