language: php

matrix:
  fast_finish: true

  include:
  - php: 7.0
    env: PHPL=1 PHPCS=1
  - php: 5.3
    env: PHPL=1
  - php: 5.4
    env: PHPL=1
  - php: 5.5
    env: PHPL=1
  - php: 5.6
    env: PHPL=1
  - php: hhvm
    env: PHPL=1

  allow_failures:
  - php: hhvm


before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $PHPL = 1 ]]; then find . -regextype posix-extended -regex "\./(lib|html/lib|vendor)" -prune -o -name "*.php" -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected' ; test $? -eq 1; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --colors --extensions=php --standard=PSR2 --ignore=html/lib/* html; fi
